apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
  name: keda-proxy
spec:
  externalName: keda-add-ons-http-interceptor-proxy.keda
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
