kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: my-nginx
spec:
    hosts:
        - www.sevgin.com	# App Ingress Hostname
    pathPrefixes:
        - /
    scaleTargetRef:
        name: my-nginx		# App Deployment Name
        kind: Deployment
        apiVersion: apps/v1
        service: my-nginx	# App Service Name
        port: 80		# App Service Port
    replicas:
        min: 1
        max: 10
    scaledownPeriod: 10
    scalingMetric:
        requestRate:		# Based on the HTTP request rate
            granularity: 1s	# The frequency of request measurement. 1s (every 1 second).
            targetValue: 2	# The target request rate. Here, it is set to 2 requests per second.
            window: 1m		# The time window for metric evaluation. It is defined as 1 minute.
