kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: my-nginx
spec:
    hosts:
        - www.sevgin.com
    pathPrefixes:
        - /
    scaleTargetRef:
        name: my-nginx
        kind: Deployment
        apiVersion: apps/v1
        service: my-nginx
        port: 80
    replicas:
        min: 1
        max: 10
    scaledownPeriod: 10
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 2
            window: 1m
